To do list add remove implementation
olanikegloria/to-do-list pull request #2
Opened 2023-06-07 21:16 UTC by olanikegloria

In this milestone I learnt to 
Use webpack to bundle JavaScript.
 Use proper ES6 syntax.
Use ES6 modules to write modular JavaScript.

2023-06-07 21:45 UTC, OyePriscilla requested changes
Hi @olanikegloria 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Implemented `Todos'` `Add` and `Edit` functionalities ✔️ 
Saved `Todos` in localstorage ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 21:45 UTC, OyePriscilla commented on src/modules/utility.js
> +    const trashBox = dotHover.querySelector('.fa-regular.fa-trash-can');
- [ ] Kindly take note that the `delete icon` is not yet displayed on the UI, I tried to hover on the the `ellipsis icon` (**the three dots**) but nothing was displayed. Kindly address this in order to have a good mastery of what's expected of you according to the project requirement. 👍

2023-06-07 21:45 UTC, OyePriscilla commented on src/style.css
> +}
- [ ] In accordande to the general requirement, please ensure that you didn't repeat the same line of code (CSS DRY principle). Thanks. 🙏

2023-06-08 10:23 UTC, uwadonat requested changes
## Hi @olanikegloria , :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

### To highlight! :+1: 
- Your commit messages are very descriptive ✔️
- Good project structure ✔️
![almost](https://github.com/olanikegloria/to-do-list/assets/65860678/d801c3fc-889b-4367-9134-0a9fe2e62e4f)

 ## Status: Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-08 10:23 UTC, uwadonat commented on README.md
> +- [Live Demo Link]()
- [ ] As requested by the previous reviewer, let's show the recruiter that you are able to pay attention to details:
 - By making sure the live demo is pointing to the deployed application or remove it from there if the project is not deployed.
 - You wrote one feature twice. remove duplication and add another one if any.
![error](https://github.com/olanikegloria/to-do-list/assets/65860678/3491642a-8ba0-428d-9be5-d28c5c492881)

2023-06-08 12:03 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @olanikegloria   👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ Successfully implement the CRUD (create, update, delete) methods👍
✔ A function for editing task descriptions is implemented. 👍 
✔ A function for deleting a task (remove an element from the array) is implemented👍
✔ All changes to the To-Do List should be saved in local storage.👍

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 12:07 UTC, merged